spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trendingsys_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwe456zym!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
